env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
  - plugin:jest/style
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
rules: 
  'jest/expect-expect': 
   - error
   - assertFunctionNames:
     - expect
     - assert
settings:
  jest:
    version: latest

ignorePatterns: 
  - generators/app/templates/example/setup.js
  - coverage
